<?xml version="1.0" encoding="utf-8"?><Database Name="NexusDB" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\NexusDB.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NexusDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Book" Member="Books">
    <Type Name="Book">
      <Column Name="book_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="author" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="genre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="language" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="isActive" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Association Name="Book_ShoppingCart" Member="ShoppingCarts" ThisKey="book_ID" OtherKey="book_ID" Type="ShoppingCart" />
      <Association Name="Book_WishList" Member="WishLists" ThisKey="book_ID" OtherKey="book_id" Type="WishList" />
      <Association Name="Book_Book_Cart" Member="Book_Carts" ThisKey="book_ID" OtherKey="book_ID" Type="Book_Cart" />
      <Association Name="Book_Review" Member="Reviews" ThisKey="book_ID" OtherKey="book_ID" Type="Review" />
      <Association Name="Book_OrderLine" Member="OrderLines" ThisKey="book_ID" OtherKey="book_ID" Type="OrderLine" />
      <Association Name="Book_Invoice_Line" Member="Invoice_Lines" ThisKey="book_ID" OtherKey="book_ID" Type="Invoice_Line" />
      <Association Name="Book_Book_WishList" Member="Book_WishLists" ThisKey="book_ID" OtherKey="wishList_ID" Type="Book_WishList" />
    </Type>
  </Table>
  <Table Name="dbo.ShoppingCart" Member="ShoppingCarts">
    <Type Name="ShoppingCart">
      <Column Name="cart_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="book_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ShoppingCart_CartItem" Member="CartItems" ThisKey="cart_Id" OtherKey="cart_ID" Type="CartItem" />
      <Association Name="Book_ShoppingCart" Member="Book" ThisKey="book_ID" OtherKey="book_ID" Type="Book" IsForeignKey="true" />
      <Association Name="User_ShoppingCart" Member="User" ThisKey="user_Id" OtherKey="user_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WishList" Member="WishLists">
    <Type Name="WishList">
      <Column Name="w_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="book_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Book_WishList" Member="Book" ThisKey="book_id" OtherKey="book_ID" Type="Book" IsForeignKey="true" />
      <Association Name="User_WishList" Member="User" ThisKey="userid" OtherKey="user_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="oder_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="satus" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="invoice_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_Invoice" Member="Invoices" ThisKey="oder_Id" OtherKey="oderID" Type="Invoice" />
      <Association Name="Order_OrderLine" Member="OrderLines" ThisKey="oder_Id" OtherKey="oderId" Type="OrderLine" />
      <Association Name="Invoice_Order" Member="Invoice" ThisKey="invoice_ID" OtherKey="invoice_ID" Type="Invoice" IsForeignKey="true" />
      <Association Name="User_Order" Member="User" ThisKey="user_id" OtherKey="user_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="invoice_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="issueDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="oderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Invoice_Order" Member="Orders" ThisKey="invoice_ID" OtherKey="invoice_ID" Type="Order" />
      <Association Name="Invoice_Invoice_Line" Member="Invoice_Lines" ThisKey="invoice_ID" OtherKey="invoice_ID" Type="Invoice_Line" />
      <Association Name="Order_Invoice" Member="Order" ThisKey="oderID" OtherKey="oder_Id" Type="Order" IsForeignKey="true" />
      <Association Name="User_Invoice" Member="User" ThisKey="user_ID" OtherKey="user_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Book_Cart" Member="Book_Carts">
    <Type Name="Book_Cart">
      <Column Name="ws_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="book_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Book_Book_Cart" Member="Book" ThisKey="book_ID" OtherKey="book_ID" Type="Book" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Review" Member="Reviews">
    <Type Name="Review">
      <Column Name="Review_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="response" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="book_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Book_Review" Member="Book" ThisKey="book_ID" OtherKey="book_ID" Type="Book" IsForeignKey="true" />
      <Association Name="User_Review" Member="User" ThisKey="user_ID" OtherKey="user_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderLine" Member="OrderLines">
    <Type Name="OrderLine">
      <Column Name="OderLineId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="priceAtOder" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="oderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="book_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_OrderLine" Member="Order" ThisKey="oderId" OtherKey="oder_Id" Type="Order" IsForeignKey="true" />
      <Association Name="Book_OrderLine" Member="Book" ThisKey="book_ID" OtherKey="book_ID" Type="Book" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice_Line" Member="Invoice_Lines">
    <Type Name="Invoice_Line">
      <Column Name="invoice_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="book_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Book_Invoice_Line" Member="Book" ThisKey="book_ID" OtherKey="book_ID" Type="Book" IsForeignKey="true" />
      <Association Name="Invoice_Invoice_Line" Member="Invoice" ThisKey="invoice_ID" OtherKey="invoice_ID" Type="Invoice" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Book_WishList" Member="Book_WishLists">
    <Type Name="Book_WishList">
      <Column Name="wishList_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="book_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Book_Book_WishList" Member="Book" ThisKey="wishList_ID" OtherKey="book_ID" Type="Book" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CartItem" Member="CartItems">
    <Type Name="CartItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cart_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BookID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ShoppingCart_CartItem" Member="ShoppingCart" ThisKey="cart_ID" OtherKey="cart_Id" Type="ShoppingCart" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="user_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="isActive" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="isLoggedin" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="User_ShoppingCart" Member="ShoppingCarts" ThisKey="user_ID" OtherKey="user_Id" Type="ShoppingCart" />
      <Association Name="User_WishList" Member="WishLists" ThisKey="user_ID" OtherKey="userid" Type="WishList" />
      <Association Name="User_Order" Member="Orders" ThisKey="user_ID" OtherKey="user_id" Type="Order" />
      <Association Name="User_Invoice" Member="Invoices" ThisKey="user_ID" OtherKey="user_ID" Type="Invoice" />
      <Association Name="User_Review" Member="Reviews" ThisKey="user_ID" OtherKey="user_ID" Type="Review" />
    </Type>
  </Table>
</Database>